languageCode: "en-us"
title: "Membership Guide"
baseURL: "https://membership-guide.civichall.org"
theme: civic-hall-base
MetaDataFormat: "yaml"
DefaultContentLanguage: "en"

params:
  logo: /uploads/logo-civic-hall-boxed.svg
  member_log_in: http://civichall.spaces.nexudus.com/en/
  sidebar_direction: sidebar_left
  description: "Welcome to a community of action-oriented, cross-sector professionals located in the heart of Manhattan, where we aim to better the world through civic tech."
  copyClass: "nested-copy-line-height nested-links nested-img mid-gray measure-wide-l"
  section_two_column_classes: "w-100 v-top column-count-2-l column-gap-1-l"
  section_flex_wrap: "flex-ns flex-wrap justify-between"
  ghcontentdir: "https://github.com/theNewDynamic/civic-hall-member-guide/tree/master/content"
taxonomies:
  tag: "tags"
  category: "categories"
  series: "series"
