DefaultContentLanguage = "en"
MetaDataFormat = "yaml"
baseURL = "https://membership-guide.civichall.org"
languageCode = "en-us"
theme = "civic-hall-base"
title = "Membership Guide"
[[menu.main]]
identifier = "membership"
name = "Slack Community"
url = "/slack/"
weight = 3
[[menu.main]]
identifier = "guidelines"
name = "Guidelines & Policies"
url = "/guidelines/"
weight = 1
[params]
description = "Welcome to a community of action-oriented, cross-sector professionals located in the heart of Manhattan, where we aim to better the world through civic tech."
facebook = "https://www.facebook.com/CivicHallNYC"
ghcontentdir = "https://github.com/theNewDynamic/civic-hall-member-guide/tree/master/content"
hero_copy = "Welcome!"
hero_link = ""
instagram = "https://www.instagram.com/civichall/"
logo = "/uploads/logo-civic-hall-boxed.svg"
member_log_in = "http://civichall.spaces.nexudus.com/en/"
sidebar_direction = "sidebar_left"
twitter = "https://twitter.com/CivicHall"
[taxonomies]
category = "categories"
series = "series"
tag = "tags"
