languageCode: "en-us"
title: "Membership Guide"
baseURL: "https://membership-guide.civichall.org"
theme: civic-hall-base
MetaDataFormat: "yaml"
DefaultContentLanguage: "en"

params:
  logo: /uploads/logo-civic-hall-boxed.svg
  member_log_in: http://civichall.spaces.nexudus.com/en/
  sidebar_direction: sidebar_left
  description: "Welcome to a community of action-oriented, cross-sector professionals located in the heart of Manhattan, where we aim to better the world through civic tech."

taxonomies:
  tag: "tags"
  category: "categories"
  series: "series"
