languageCode: "en-us"
title: "Civic Hall Membership Guide"
baseURL: "https://membership-guide.civichall.org"
theme: civic-hall-base

description: "Welcome to a community of action-oriented, cross-sector professionals located in the heart of Manhattan, where we aim to better the world through civic tech."
