---
new_page_extension: md
auto_deploy: false
admin_path: admin
webhook_url: 
sections: 
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: "/uploads"
use_front_matter_path: false
file_template: ":filename:"
version: 0.20.2
