---
pages:
- announcements/announcements-2.12.18.md
- announcements/announcements-2.5.18.md
- announcements/announcements-1.29.18.md
- announcements/announcements-1.22.18.md
- announcements/announcements-1.16.18.md
- announcements/announcements-12.18.17.md
- announcements/announcements-12.11.17.md
- announcements/announcements-12.4.17.md
- announcements/announcements-11.27.17.md
- announcements/announcements-11.20.17.md
- announcements/announcements-10.9.17.md
- announcements/announcements-10.16.17.md
- announcements/announcements-10.23.17.md
- announcements/announcements-10.30.17.md
- announcements/announcements-11.6.17.md
- announcements/announcements-11.13.17.md
- announcements/announcements-10-2-17.md
- announcements/we-re-open-on-columbus-day-october-9.md
- announcements/meet-our-summer-interns.md
- membership/membership/aws-activate--offer-for-civic-hall-members.md
hide_body: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: date
  label: Date
  type: text
  hidden: false
  default: ''
- name: tags
  label: Tags
  type: tag_list
  hidden: false
  default: []
- name: featured_image
  label: Featured image
  type: text
  hidden: false
  default: ''
