---
hide_body: false
is_partial: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: date
  label: Date
  type: text
  hidden: false
  default: ''
- name: tags
  label: Tags
  type: tag_list
  hidden: false
  default: []
- name: featured_image
  label: Featured image
  type: text
  hidden: false
  default: ''
pages:
- content/announcements/announcements-6.25.18.md
- content/announcements/announcements-6.18.18.md
- content/announcements/announcements-5.14.18.md
- content/announcements/announcements-2.5.18.md
- content/announcements/announcements-2.12.18.md
- content/announcements/announcements-.md
- content/announcements/meet-our-summer-interns.md
- content/announcements/announcements-4.2.18.md
- content/announcements/announcements-5.7.18.md
- content/announcements/announcements-3.12.18.md
- content/announcements/announcements-3.5.18.md
- content/announcements/announcements-2.20.18.md
- content/announcements/announcements-1.29.18.md
- content/announcements/announcements-1.16.18.md
- content/announcements/announcements-12.4.17.md
- content/announcements/announcements-11.27.17.md
- content/announcements/announcements-11.20.17.md
- content/announcements/announcements-10.9.17.md
- content/announcements/announcements-11.6.17.md
- content/announcements/announcements-11.13.17.md
- content/announcements/we-re-open-on-columbus-day-october-9.md
- content/announcements/announcements-10.16.17.md
- content/announcements/announcements-5.21.18.md
- content/announcements/announcements-4.16.18.md
- content/announcements/announcements-6.11.18.md
- content/announcements/announcements-12.18.17.md
- content/announcements/announcements-3.19.18.md
- content/announcements/announcements-1.22.18.md
- content/announcements/announcements-10.23.17.md
- content/announcements/announcements-10.30.17.md
- content/announcements/announcements-2.26.18.md
- content/announcements/announcements-4.30.18.md
- content/announcements/announcements-4.23.18.md
- content/announcements/announcements-4.9.18.md
- content/announcements/announcements-12.11.17.md
- content/announcements/announcements-10-2-17.md
- content/membership/membership/aws-activate--offer-for-civic-hall-members.md
